version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/ui/static
    depends_on:
      - db

  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./database.db:/data/database.db
